### ISSUE TITLE
How to change the direction of the slider? (Right to left)

### ISSUE THREAD

**Issue by Daariush** [agentS/react-native-slider-button#1]
I've successfully installed it on the project and also change the styling but i'm looking forward how to change the direction of the slider to "**right to left**" instead of left to right.

Help needed, thanks in advance.

**Comment by agentS** [comment]
I think that is a feature I have not implemented yet. I am going to 
investigate this tomorrow morning and create a new revision allowing the 
slider to be moved from right to left.

Am 14.06.2016 um 09:41 schrieb Dariush:

**Comment by agentS** [comment]
I have just added the new `rightToLeft` property which has to be set to true. Please see the following example:

```
<SliderButton key={this.state.timestamp}
    text={"Activate >>>"}
    textAnimated={true}
    stylesheet={SliderButtonStyle}
    rightToLeft={true}
    minimumTrackTintColor={"rgba(0,0,0,0)"}
    maximumTrackTintColor={"rgba(0,0,0,0)"}
    onTrigger={this.onSliderButtonActivated}/>
```

I am closing this issue.

**Comment by Daariush** [comment]
Thanks alot @agentS for the quick fix 👍
